
export const Chats = [
{   id: "js1",
    name: "Farhod Dadajonov",
    image: "/images/farhod-dadajonov.jpg",
    uploadedDate: "2018",
    typeOfVideos: "javaScript",
    numOfVideos: "36",
    chanelTitle:"Murakkablikdan soddalikkacha"
},
{   id: "js2",
    name: "Farhod Dadajonov",
    image: "/images/farhod-dadajonov.jpg",
    uploadedDate: "2018",
    typeOfVideos: "javaScript",
    numOfVideos: "36",
    chanelTitle:"Murakkablikdan soddalikkacha"
},
{   id: "js3",
    name: "Farhod Dadajonov",
    image: "/images/farhod-dadajonov.jpg",
    uploadedDate: "2018",
    typeOfVideos: "javaScript",
    numOfVideos: "36",
    chanelTitle:"Murakkablikdan soddalikkacha"
},
{   id: "js4",
    name: "Farhod Dadajonov",
    image: "/images/farhod-dadajonov.jpg",
    uploadedDate: "2018",
    typeOfVideos: "javaScript",
    numOfVideos: "36",
    chanelTitle:"Murakkablikdan soddalikkacha"
},
{   id: "js5",
    name: "Farhod Dadajonov",
    image: "/images/farhod-dadajonov.jpg",
    uploadedDate: "2018",
    typeOfVideos: "javaScript",
    numOfVideos: "36",
    chanelTitle:"Murakkablikdan soddalikkacha"
},
{   id: "js6",
    name: "Farhod Dadajonov",
    image: "/images/farhod-dadajonov.jpg",
    uploadedDate: "2018",
    typeOfVideos: "javaScript",
    numOfVideos: "36",
    chanelTitle:"Murakkablikdan soddalikkacha"
},
{   id: "js7",
    name: "Farhod Dadajonov",
    image: "/images/farhod-dadajonov.jpg",
    uploadedDate: "2018",
    typeOfVideos: "javaScript",
    numOfVideos: "36",
    chanelTitle:"Murakkablikdan soddalikkacha"
},
{   id: "js8",
    name: "Farhod Dadajonov",
    image: "/images/farhod-dadajonov.jpg",
    uploadedDate: "2018",
    typeOfVideos: "javaScript",
    numOfVideos: "36",
    chanelTitle:"Murakkablikdan soddalikkacha"
}
];